### ISSUE TITLE
acceptable usage/modification of the logo?

### ISSUE THREAD

**Issue by ha0ye** [carpentries/logo#8]
Hi,

The UF Carpentries club is close to settling on a final design for our logo, derived from the new Carpentries person/wrench design. We may make some tweaks to colors and line thicknesses, but would this design be acceptable usage/modification?

[uf-carpentries-blue-border.pdf](https://github.com/carpentries/logo/files/3199228/uf-carpentries-blue-border.pdf)

[see also UF-Carpentry/Coordination#31]

Thanks!

**Comment by tracykteal** [comment]
Yes, thanks! That would be acceptable use, given that it's similar but different enough and for an organization for Carpentries activities.

**Comment by davidyakobovitch** [comment]
This issue should be closed out.
